account_id = "049ff5e84ecf636b53b162cbb580aae6"
name = "travlog-ai"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "TRAVLOG_KV"
id = "fa628f33a9c54f3789c4711a0351d6d7"

[vars]
AGENT_NAME = "TravLog"
AGENT_TONE = "adventurous, practical, detailed"
AGENT_AVATAR = "✈️"
